version: '3.1'
services:
  web:
    container_name: channel_web
    build: .
    volumes:
      - .:/app
    command: ["sh", "run.sh"]
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - channel-network
  redis:
    container_name: channel_redis
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - channel-network
networks:
  channel-network: